# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 06:50
from __future__ import unicode_literals

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20171005_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_1',
            field=users.fields.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='scans', verbose_name='Document scan 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_2',
            field=users.fields.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='scans', verbose_name='Document scan 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_3',
            field=users.fields.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='scans', verbose_name='Document scan 3'),
        ),
    ]
