# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_donations_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='address',
            new_name='donation_address',
        ),
    ]
