# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='tokens',
            field=models.FloatField(blank=True, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0442\u043e\u043a\u0435\u043d\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='donation',
            name='tx_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438'),
        ),
    ]
