# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_site', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u0441\u0430\u0439\u0442')),
                ('main_block_title', models.CharField(default='We integrates the blockchain of 60 million golfers', max_length=128, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('main_block_title_en', models.CharField(default='We integrates the blockchain of 60 million golfers', max_length=128, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('main_block_title_ru', models.CharField(default='We integrates the blockchain of 60 million golfers', max_length=128, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('main_block_title_zh', models.CharField(default='We integrates the blockchain of 60 million golfers', max_length=128, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('main_block_subtitle', models.CharField(default='Discount for early investors up to 40%', max_length=128, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('main_block_subtitle_en', models.CharField(default='Discount for early investors up to 40%', max_length=128, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('main_block_subtitle_ru', models.CharField(default='Discount for early investors up to 40%', max_length=128, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('main_block_subtitle_zh', models.CharField(default='Discount for early investors up to 40%', max_length=128, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('main_block_start_link', models.CharField(blank=True, max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u0432 \u043a\u043d\u043e\u043f\u043a\u0435 "Start Pre-ICO"')),
                ('main_block_whitepaper_link', models.CharField(blank=True, max_length=255, verbose_name="\u0421\u0441\u044b\u043b\u043a\u0430 \u0432 \u043a\u043d\u043e\u043f\u043a\u0435 'Whitepaper'")),
                ('main_block_timer_text', models.CharField(default='Pre-ICO tokens golfcoin starts through', max_length=128, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0442\u0430\u0439\u043c\u0435\u0440\u0430')),
                ('main_block_timer_text_en', models.CharField(default='Pre-ICO tokens golfcoin starts through', max_length=128, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0442\u0430\u0439\u043c\u0435\u0440\u0430')),
                ('main_block_timer_text_ru', models.CharField(default='Pre-ICO tokens golfcoin starts through', max_length=128, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0442\u0430\u0439\u043c\u0435\u0440\u0430')),
                ('main_block_timer_text_zh', models.CharField(default='Pre-ICO tokens golfcoin starts through', max_length=128, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0442\u0430\u0439\u043c\u0435\u0440\u0430')),
                ('show_timer', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0442\u0430\u0439\u043c\u0435\u0440')),
                ('main_email', models.EmailField(default='support@golfcoin.club', max_length=128, verbose_name='Email')),
                ('about_title', models.CharField(default='What is Golfcoin?', max_length=128, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'")),
                ('about_title_en', models.CharField(default='What is Golfcoin?', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'")),
                ('about_title_ru', models.CharField(default='What is Golfcoin?', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'")),
                ('about_title_zh', models.CharField(default='What is Golfcoin?', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'")),
                ('about_text', models.TextField(blank=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'")),
                ('about_text_en', models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'")),
                ('about_text_ru', models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'")),
                ('about_text_zh', models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'")),
                ('about_address', models.CharField(max_length=128, verbose_name="\u0410\u0434\u0440\u0435\u0441 \u0432 \u0431\u043b\u043e\u043a\u0435 '\u041e \u043d\u0430\u0441'")),
                ('social_in', models.CharField(blank=True, help_text='https://linkedin.com/golfco', max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 Linkedin')),
                ('social_fb', models.CharField(blank=True, help_text='https://facebook.com/golfco', max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 Facebook')),
                ('social_insta', models.CharField(blank=True, help_text='https://instagram.com/golfco', max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 Instagram')),
                ('social_twi', models.CharField(blank=True, help_text='https://twitter.com/golfco', max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 Twitter')),
                ('social_telegram', models.CharField(blank=True, help_text='https://t.co/golfco', max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 Telegram')),
                ('investments_eth', models.IntegerField(verbose_name='\u0418\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043e ETH')),
                ('investments_participants', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u0432\u0448\u0438\u0445')),
                ('project_plan_title', models.CharField(default='Roadmap', max_length=128, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Roadmap'")),
                ('project_plan_title_en', models.CharField(default='Roadmap', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Roadmap'")),
                ('project_plan_title_ru', models.CharField(default='Roadmap', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Roadmap'")),
                ('project_plan_title_zh', models.CharField(default='Roadmap', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Roadmap'")),
                ('project_plan_date1', models.DateField(blank=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0434\u0430\u0442\u0430)')),
                ('project_plan_text1', models.CharField(blank=True, max_length=128, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text1_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text1_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text1_zh', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_date2', models.DateField(blank=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0434\u0430\u0442\u0430)')),
                ('project_plan_text2', models.CharField(blank=True, max_length=128, verbose_name='\u041f\u043b\u0430\u043d 2 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text2_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 2 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text2_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 2 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text2_zh', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 2 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_date3', models.DateField(blank=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0434\u0430\u0442\u0430)')),
                ('project_plan_text3', models.CharField(blank=True, max_length=128, verbose_name='\u041f\u043b\u0430\u043d 3 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text3_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 3 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text3_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 3 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text3_zh', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 3 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_date4', models.DateField(blank=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0434\u0430\u0442\u0430)')),
                ('project_plan_text4', models.CharField(blank=True, max_length=128, verbose_name='\u041f\u043b\u0430\u043d 4 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text4_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 4 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text4_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 4 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text4_zh', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 4 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_date5', models.DateField(blank=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0434\u0430\u0442\u0430)')),
                ('project_plan_text5', models.CharField(blank=True, max_length=128, verbose_name='\u041f\u043b\u0430\u043d 5 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text5_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 5 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text5_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 5 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text5_zh', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 5 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_date6', models.DateField(blank=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0434\u0430\u0442\u0430)')),
                ('project_plan_text6', models.CharField(blank=True, max_length=128, verbose_name='\u041f\u043b\u0430\u043d 6 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text6_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 6 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text6_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 6 (\u0442\u0435\u043a\u0441\u0442)')),
                ('project_plan_text6_zh', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 6 (\u0442\u0435\u043a\u0441\u0442)')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f \u0441\u0430\u0439\u0442\u0430',
            },
        ),
    ]
