# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='investments_eth',
            field=models.IntegerField(default=0, verbose_name='\u0418\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043e ETH'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='investments_participants',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u0432\u0448\u0438\u0445'),
        ),
    ]
