# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20170922_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='project_plan_date6',
            field=models.DateField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u043d 6 (\u0434\u0430\u0442\u0430)'),
        ),
    ]
