# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20170922_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_block_html_id',
            field=models.CharField(default='about', max_length=32, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_html_id',
            field=models.CharField(default='roadmap', max_length=32, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
    ]
