# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20170922_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='name_zh',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='position_en',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='position_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='position_zh',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='teammatecategory',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='teammatecategory',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='teammatecategory',
            name='name_zh',
            field=models.CharField(max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
    ]
