# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_auto_20170922_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='team', verbose_name='\u0424\u043e\u0442\u043e')),
                ('name', models.CharField(max_length=128, verbose_name='\u0418\u043c\u044f')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f')),
                ('name_zh', models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0432\u0435\u0442\u043d\u0438\u043a (Advisor)',
                'verbose_name_plural': '\u0421\u043e\u0432\u0435\u0442\u043d\u0438\u043a\u0438 (Advisors)',
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advisor_block_title',
            field=models.CharField(default='Advisors', max_length=128, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Advisors'"),
        ),
        migrations.AddField(
            model_name='advisor',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='config.SiteConfiguration', verbose_name='\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0441\u0430\u0439\u0442\u0430'),
        ),
    ]
