# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_auto_20170922_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='timer_deadline',
            field=models.DateField(default='2017-10-30', help_text='\u0414\u0430\u0442\u0430 \u0434\u043b\u044f \u0442\u0430\u0439\u043c\u0435\u0440\u0430', verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043f\u0443\u0441\u043a\u0430 \u043f\u0440\u043e\u0435\u043a\u0442\u0430'),
        ),
    ]
