# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('question_en', models.CharField(max_length=128, null=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('question_ru', models.CharField(max_length=128, null=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('question_zh', models.CharField(max_length=128, null=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('answer', models.TextField(verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('answer_en', models.TextField(null=True, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('answer_ru', models.TextField(null=True, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('answer_zh', models.TextField(null=True, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441-\u041e\u0442\u0432\u0435\u0442',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b-\u041e\u0442\u0432\u0435\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='faq_block_title',
            field=models.CharField(default='FAQ', max_length=128, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'FAQ'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='faq_block_title_en',
            field=models.CharField(default='FAQ', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'FAQ'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='faq_block_title_ru',
            field=models.CharField(default='FAQ', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'FAQ'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='faq_block_title_zh',
            field=models.CharField(default='FAQ', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'FAQ'"),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='config.SiteConfiguration', verbose_name='\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0441\u0430\u0439\u0442\u0430'),
        ),
    ]
