# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_auto_20170927_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='name_de',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='name_es',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='answer_de',
            field=models.TextField(null=True, verbose_name='\u041e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='answer_es',
            field=models.TextField(null=True, verbose_name='\u041e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='question_de',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='question_es',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_de',
            field=models.TextField(max_length=256, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_es',
            field=models.TextField(max_length=256, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_text_de',
            field=models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_text_es',
            field=models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_title_de',
            field=models.CharField(default='What is Golfcoin?', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_title_es',
            field=models.CharField(default='What is Golfcoin?', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041e \u043d\u0430\u0441'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advisor_block_title_de',
            field=models.CharField(default='Advisors', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Advisors'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advisor_block_title_es',
            field=models.CharField(default='Advisors', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Advisors'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='faq_block_title_de',
            field=models.CharField(default='FAQ', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'FAQ'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='faq_block_title_es',
            field=models.CharField(default='FAQ', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'FAQ'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_block_subtitle_de',
            field=models.CharField(default='Discount for early investors up to 40%', max_length=128, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_block_subtitle_es',
            field=models.CharField(default='Discount for early investors up to 40%', max_length=128, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_block_timer_text_de',
            field=models.CharField(default='Pre-ICO tokens golfcoin starts through', max_length=128, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0442\u0430\u0439\u043c\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_block_timer_text_es',
            field=models.CharField(default='Pre-ICO tokens golfcoin starts through', max_length=128, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0442\u0430\u0439\u043c\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_block_title_de',
            field=models.CharField(default='We integrates the blockchain of 60 million golfers', max_length=128, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_block_title_es',
            field=models.CharField(default='We integrates the blockchain of 60 million golfers', max_length=128, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_block_whitepaper_link_de',
            field=models.FileField(null=True, upload_to='whitepapers', verbose_name='Whitepaper'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_block_whitepaper_link_es',
            field=models.FileField(null=True, upload_to='whitepapers', verbose_name='Whitepaper'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partners_block_title_de',
            field=models.CharField(default='Our partners', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Our partners'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partners_block_title_es',
            field=models.CharField(default='Our partners', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Our partners'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text1_de',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text1_es',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 1 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text2_de',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 2 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text2_es',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 2 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text3_de',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 3 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text3_es',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 3 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text4_de',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 4 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text4_es',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 4 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text5_de',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 5 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text5_es',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 5 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text6_de',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 6 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_text6_es',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u043b\u0430\u043d 6 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_title_de',
            field=models.CharField(default='Roadmap', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Roadmap'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='project_plan_title_es',
            field=models.CharField(default='Roadmap', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Roadmap'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='team_block_title_de',
            field=models.CharField(default='Team', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Team'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='team_block_title_es',
            field=models.CharField(default='Team', max_length=128, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Team'"),
        ),
        migrations.AddField(
            model_name='teammate',
            name='name_de',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='name_es',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='position_de',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='position_es',
            field=models.CharField(max_length=128, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
    ]
