# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_auto_20170927_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_de',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u041d\u0435\u043c\u0435\u0446\u043a\u0438\u0439 \u044f\u0437\u044b\u043a'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_es',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0418\u0441\u043f\u0430\u043d\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_zh',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u041a\u0438\u0442\u0430\u0439\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a'),
        ),
    ]
