# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_auto_20170927_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u041f\u0435\u0440\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_1_de',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u041f\u0435\u0440\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_1_en',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u041f\u0435\u0440\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_1_es',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u041f\u0435\u0440\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_1_ru',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u041f\u0435\u0440\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_1_zh',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u041f\u0435\u0440\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u0412\u0442\u043e\u0440\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_2_de',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u0412\u0442\u043e\u0440\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_2_en',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u0412\u0442\u043e\u0440\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_2_es',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u0412\u0442\u043e\u0440\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_2_ru',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u0412\u0442\u043e\u0440\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_img_2_zh',
            field=models.ImageField(blank=True, null=True, upload_to='details', verbose_name="\u0412\u0442\u043e\u0440\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Details'"),
        ),
    ]
