# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_auto_20170928_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='advisor_block_html_id',
            field=models.CharField(default='advisor', max_length=16, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_block_html_id',
            field=models.CharField(default='details', max_length=16, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='faq_block_html_id',
            field=models.CharField(default='faq-block', max_length=16, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='how_block_html_id',
            field=models.CharField(default='how-it-works', max_length=16, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partners_block_html_id',
            field=models.CharField(default='partners', max_length=16, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='subscribe_block_html_id',
            field=models.CharField(default='subscribe', max_length=16, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='subscribe_block_title',
            field=models.CharField(default='Get the most latest news', max_length=64, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Subscription'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='subscribe_block_title_de',
            field=models.CharField(default='Get the most latest news', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Subscription'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='subscribe_block_title_en',
            field=models.CharField(default='Get the most latest news', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Subscription'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='subscribe_block_title_es',
            field=models.CharField(default='Get the most latest news', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Subscription'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='subscribe_block_title_ru',
            field=models.CharField(default='Get the most latest news', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Subscription'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='subscribe_block_title_zh',
            field=models.CharField(default='Get the most latest news', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 'Subscription'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='team_block_html_id',
            field=models.CharField(default='team', max_length=16, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_block_html_id',
            field=models.CharField(default='about', max_length=16, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='project_plan_html_id',
            field=models.CharField(default='roadmap', max_length=16, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 HTML'),
        ),
    ]
