# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_auto_20170929_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='discount_block_text',
            field=models.CharField(default='Discount for early investors', max_length=64, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a 'Discount'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='discount_block_text_de',
            field=models.CharField(default='Discount for early investors', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a 'Discount'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='discount_block_text_en',
            field=models.CharField(default='Discount for early investors', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a 'Discount'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='discount_block_text_es',
            field=models.CharField(default='Discount for early investors', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a 'Discount'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='discount_block_text_ru',
            field=models.CharField(default='Discount for early investors', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a 'Discount'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='discount_block_text_zh',
            field=models.CharField(default='Discount for early investors', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a 'Discount'"),
        ),
    ]
