# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_auto_20170929_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='login_form_text',
            field=models.TextField(default='To pay for other types of crypto currency (BTC, ETC, LTC etc)\nPlease sign up or log in to your account', verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0444\u043e\u0440\u043c\u044b \u0432\u0445\u043e\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='login_form_text_de',
            field=models.TextField(default='To pay for other types of crypto currency (BTC, ETC, LTC etc)\nPlease sign up or log in to your account', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0444\u043e\u0440\u043c\u044b \u0432\u0445\u043e\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='login_form_text_en',
            field=models.TextField(default='To pay for other types of crypto currency (BTC, ETC, LTC etc)\nPlease sign up or log in to your account', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0444\u043e\u0440\u043c\u044b \u0432\u0445\u043e\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='login_form_text_es',
            field=models.TextField(default='To pay for other types of crypto currency (BTC, ETC, LTC etc)\nPlease sign up or log in to your account', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0444\u043e\u0440\u043c\u044b \u0432\u0445\u043e\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='login_form_text_ru',
            field=models.TextField(default='To pay for other types of crypto currency (BTC, ETC, LTC etc)\nPlease sign up or log in to your account', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0444\u043e\u0440\u043c\u044b \u0432\u0445\u043e\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='login_form_text_zh',
            field=models.TextField(default='To pay for other types of crypto currency (BTC, ETC, LTC etc)\nPlease sign up or log in to your account', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0444\u043e\u0440\u043c\u044b \u0432\u0445\u043e\u0434\u0430'),
        ),
    ]
