# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_auto_20170929_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_block_title',
            field=models.CharField(default='Details', max_length=32, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Detail'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_block_title_de',
            field=models.CharField(default='Details', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Detail'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_block_title_en',
            field=models.CharField(default='Details', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Detail'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_block_title_es',
            field=models.CharField(default='Details', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Detail'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_block_title_ru',
            field=models.CharField(default='Details', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Detail'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='details_block_title_zh',
            field=models.CharField(default='Details', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Detail'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='how_block_block_title',
            field=models.CharField(default='How it works', max_length=32, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'How it works'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='how_block_block_title_de',
            field=models.CharField(default='How it works', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'How it works'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='how_block_block_title_en',
            field=models.CharField(default='How it works', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'How it works'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='how_block_block_title_es',
            field=models.CharField(default='How it works', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'How it works'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='how_block_block_title_ru',
            field=models.CharField(default='How it works', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'How it works'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='how_block_block_title_zh',
            field=models.CharField(default='How it works', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'How it works'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_block_title',
            field=models.CharField(default='Join Us', max_length=32, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_block_title_de',
            field=models.CharField(default='Join Us', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_block_title_en',
            field=models.CharField(default='Join Us', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_block_title_es',
            field=models.CharField(default='Join Us', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_block_title_ru',
            field=models.CharField(default='Join Us', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_block_title_zh',
            field=models.CharField(default='Join Us', max_length=32, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b'"),
        ),
    ]
