# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_auto_20171001_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.CharField(blank=True, max_length=5, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_text',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a \u0441\u043a\u0438\u0434\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_text_de',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a \u0441\u043a\u0438\u0434\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_text_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a \u0441\u043a\u0438\u0434\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_text_es',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a \u0441\u043a\u0438\u0434\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_text_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a \u0441\u043a\u0438\u0434\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_text_zh',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a \u0441\u043a\u0438\u0434\u043a\u0435'),
        ),
    ]
