# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_auto_20171005_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_policy',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Privacy Policy'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_policy_de',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Privacy Policy'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_policy_en',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Privacy Policy'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_policy_es',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Privacy Policy'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_policy_ru',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Privacy Policy'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_policy_zh',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Privacy Policy'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='terms_and_conditions',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='terms_and_conditions_de',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='terms_and_conditions_en',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='terms_and_conditions_es',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='terms_and_conditions_ru',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='terms_and_conditions_zh',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 Terms & Conditions'),
        ),
    ]
