# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_donation_addresses'),
        ('config', '0029_auto_20171005_0906'),
    ]

    operations = [
    ]
