# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_auto_20171009_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_rules',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Document scan rules'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_rules_de',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Document scan rules'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_rules_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Document scan rules'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_rules_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Document scan rules'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_rules_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Document scan rules'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_rules_zh',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Document scan rules'),
        ),
    ]
