# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_auto_20171013_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='opyt',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041e\u043f\u044b\u0442 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
    ]
