# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_auto_20171013_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='experience',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041e\u043f\u044b\u0442 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='experience',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041e\u043f\u044b\u0442 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='experience_de',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041e\u043f\u044b\u0442 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='experience_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041e\u043f\u044b\u0442 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='experience_es',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041e\u043f\u044b\u0442 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='experience_ru',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041e\u043f\u044b\u0442 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='experience_zh',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041e\u043f\u044b\u0442 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
    ]
