# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_auto_20171024_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='investments_currency_hard',
            field=models.CharField(default='ETH', max_length=10, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='investments_currency_soft',
            field=models.CharField(default='USD', max_length=10, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='investments_eth_hard',
            field=models.IntegerField(default=0, verbose_name='\u0418\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043e USD/ETH (Hard Cap)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='investments_eth_soft',
            field=models.IntegerField(default=0, verbose_name='\u0418\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043e USD/ETH (Soft Cap)'),
        ),
    ]
