# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0038_auto_20171024_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='investments_currency_hard',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='investments_currency_soft',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='investments_eth_hard',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='investments_eth_soft',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='investments_participants_hard',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='investments_participants_soft',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hardcap',
            field=models.IntegerField(default=0, verbose_name='Hard Cap'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hardcap_currency',
            field=models.CharField(default='ETH', max_length=10, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430 (Hard Cap)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='investments_eth',
            field=models.IntegerField(default=0, verbose_name='\u0418\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043e ETH'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='investments_participants',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u0432\u0448\u0438\u0445'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='softcap',
            field=models.IntegerField(default=0, verbose_name='Soft Cap'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='softcap_currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430 (Soft Cap)'),
        ),
    ]
