# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0035_auto_20171029_1833'),
        ('config', '0039_auto_20171027_1223'),
    ]

    operations = [
    ]
