# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_merge_20171029_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='faq_block_bg',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='\u0424\u043e\u043d\u043e\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_bg',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='\u0424\u043e\u043d \u0432 \u0445\u0435\u0434\u0435\u0440\u0435'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='how_block_bg',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='\u0424\u043e\u043d\u043e\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='team_block_bg',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='\u0424\u043e\u043d\u043e\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
