# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170922_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name_en_us',
            new_name='name_en',
        ),
    ]
